# Stores the 'global' arguments for the repository

# PROJECT metadata
project:
    name: rainbow
    version: 1.1.0
    author: VOYEUX Alfred
    description: "3D visualization and re-projection of a solar protuberance."

# ROOTPATH project
root_path: &root !rootpath  # setting the root path dynamically

# PATHs
# DIRECTORIEs
dir:
    _path: &_dir !join [*root, 'data']

    input:
        _path: &input !join [*_dir, 'input']
