# Stores the 'global' arguments for the repository

# PROJECT metadata
project:
    name: rainbow
    version: 1.1.0
    author: VOYEUX Alfred
    description: "3D visualization and re-projection of a solar protuberance."

# ROOTPATH project
root_path: &root !rootpath  # dynamic root path (where virtual env is)

# PATHs
dir:
    _path: &_dir !join [*root, 'data']

    temporary: !join [*_dir, 'temporary']

    input:
        path: &_input !join [*_dir, 'input']

        texture: !join [*_input, 'texture']
        cubes: !join [*_input, 'cubes']
        envelope: !join [*_input, 'envelope']

        sdo:  # todo check if png path needed here or in 'output'
            _path: &_sdo !join [*_input, 'sdo']

            fits: *_sdo
            png: !join [*_sdo, 'png']

        stereo:
            _path: &_stereo !join [*_input, 'stereo']

            avg: !join [*_stereo, 'avg']
            int: !join [*_stereo, 'int']
            masque: !join [*_stereo, 'masque']
            masque_karine: !join [*_stereo, 'masque_karine']

    output:
        _path: &_output !join [*_dir, 'output']

        hdf5: !join [*_output, 'hdf5']
        mp4_saves: !join [*_output, 'mp4_saves']

        results:
            _path: &_results !join [*_output, 'results']

            contours: !join [*_results, 'contours']
            envelope: !join [*_results, 'envelope']
            feet: !join [*_results, 'feet']
            volume: !join [*_results, 'volume']

            textures:
                _path: &_textures !join [*_results, 'textures']

                plots: !join [*_textures, 'plots']
                screenshots: !join [*_textures, 'screenshots']

            projection:
                _path: &_projection !join [*_results, 'projection']

                sdo: !join [*_projection, 'sdo']
                warped: !join [*_projection, 'warped']
                integration: !join [*_projection, 'integration']

file:
    stereo_info: !join [*_stereo, 'stereo_304.save']
    timestamps: !join [*_input, 'SDO_timestamps.txt']
